import { useEffect, useState } from "react";

const SUPABASE_URL="https://pekpyiyivttrjjxsrarx.supabase.co";
const SUPABASE_KEY="sb_publishable_byqYtROGi5NKkIWiZJ07uw_RMPhuMzS";
type Review={id:number;guest_name:string;visit_type:string;rating:number;review_text:string;photo_urls:string[];approved:boolean;created_at:string};

async function api(path:string,token:string,options:RequestInit={}){
 return fetch(`${SUPABASE_URL}${path}`,{...options,headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${token}`,"Content-Type":"application/json",...(options.headers||{})}});
}
function Photos({paths,token}:{paths:string[];token:string}){
 const [urls,setUrls]=useState<string[]>([]);
 useEffect(()=>{let ok=true;Promise.all((paths||[]).map(async p=>{const r=await api(`/storage/v1/object/sign/guest-photos/${encodeURIComponent(p)}`,token,{method:"POST",body:JSON.stringify({expiresIn:3600})});if(!r.ok)return "";const d=await r.json();return d.signedURL?`${SUPABASE_URL}/storage/v1${d.signedURL}`:""})).then(x=>ok&&setUrls(x.filter(Boolean)));return()=>{ok=false}},[paths,token]);
 if(!urls.length)return null; return <div className="grid grid-cols-3 gap-2 mt-4">{urls.map((u,i)=><img key={u} src={u} alt={`Misafir fotoğrafı ${i+1}`} className="w-full h-28 object-cover rounded-xl"/>)}</div>
}
export default function AdminPanel(){
 const [token,setToken]=useState(()=>sessionStorage.getItem("golkoy_admin_token")||"");
 const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(false);
 const load=async(t=token)=>{if(!t)return;setLoading(true);const r=await api("/rest/v1/guest_reviews?select=*&order=created_at.desc",t);if(r.status===401){sessionStorage.removeItem("golkoy_admin_token");setToken("");setError("Oturum süresi doldu.");setLoading(false);return}setReviews(r.ok?await r.json():[]);setLoading(false)};
 useEffect(()=>{if(token)load(token)},[token]);
 const login=async(e:React.FormEvent)=>{e.preventDefault();setError("");const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify({email,password})});const d=await r.json();if(!r.ok){setError("E-posta veya şifre hatalı.");return}sessionStorage.setItem("golkoy_admin_token",d.access_token);setToken(d.access_token);setPassword("")};
 const update=async(id:number,approved:boolean)=>{const r=await api(`/rest/v1/guest_reviews?id=eq.${id}`,token,{method:"PATCH",headers:{Prefer:"return=minimal"},body:JSON.stringify({approved})});if(r.ok)load()};
 const remove=async(r:Review)=>{if(!confirm("Bu yorumu kalıcı olarak silmek istiyor musunuz?"))return;for(const p of r.photo_urls||[])await api(`/storage/v1/object/guest-photos/${encodeURIComponent(p)}`,token,{method:"DELETE"});const x=await api(`/rest/v1/guest_reviews?id=eq.${r.id}`,token,{method:"DELETE"});if(x.ok)load()};
 const logout=()=>{sessionStorage.removeItem("golkoy_admin_token");setToken("");setReviews([])};
 if(!token)return <main className="min-h-screen bg-slate-100 flex items-center justify-center p-4"><form onSubmit={login} className="bg-white w-full max-w-md rounded-3xl shadow-xl p-8"><img src="./amblem.jpg" className="w-20 h-20 object-contain mx-auto" /><h1 className="text-2xl font-bold text-center mt-3">Yönetici Paneli</h1><p className="text-gray-500 text-center mt-2">Gölköy Yaşam Resort</p><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="E-posta" className="w-full border rounded-xl px-4 py-3 mt-7"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Şifre" className="w-full border rounded-xl px-4 py-3 mt-3"/>{error&&<p className="text-red-600 text-sm mt-3">{error}</p>}<button className="w-full bg-amber-500 text-white font-semibold rounded-xl py-3 mt-5">Giriş Yap</button><a href="./" className="block text-center text-sm text-gray-500 mt-5">← Siteye dön</a></form></main>;
 return <main className="min-h-screen bg-slate-100"><header className="bg-white border-b"><div className="max-w-6xl mx-auto p-4 flex items-center justify-between"><div className="flex items-center gap-3"><img src="./amblem.jpg" className="w-12 h-12 object-contain"/><div><strong>Gölköy Yaşam Resort</strong><div className="text-sm text-gray-500">Yönetici Paneli</div></div></div><button onClick={logout} className="border rounded-xl px-4 py-2">Çıkış Yap</button></div></header><section className="max-w-6xl mx-auto p-4 md:p-8"><div className="flex justify-between items-end mb-6"><div><h1 className="text-3xl font-bold">Misafir Yorumları</h1><p className="text-gray-500 mt-1">Bekleyen yorumları inceleyin ve yayın durumunu yönetin.</p></div><button onClick={()=>load()} className="border bg-white rounded-xl px-4 py-2">Yenile</button></div>{loading?<p>Yükleniyor...</p>:reviews.length===0?<div className="bg-white rounded-2xl p-8 text-center">Henüz yorum bulunmuyor.</div>:<div className="grid md:grid-cols-2 gap-5">{reviews.map(r=><article key={r.id} className="bg-white rounded-2xl p-6 shadow-sm border"><div className="flex justify-between gap-3"><div><span className="text-amber-500">{"★".repeat(r.rating)}{"☆".repeat(5-r.rating)}</span><h2 className="font-bold text-lg mt-2">{r.guest_name}</h2><span className="text-sm text-gray-500">{r.visit_type} · {new Date(r.created_at).toLocaleString("tr-TR")}</span></div><span className={`h-fit px-3 py-1 rounded-full text-sm font-medium ${r.approved?"bg-green-100 text-green-700":"bg-amber-100 text-amber-800"}`}>{r.approved?"Yayında":"Onay Bekliyor"}</span></div><p className="mt-4 text-gray-700">“{r.review_text}”</p><Photos paths={r.photo_urls||[]} token={token}/><div className="flex flex-wrap gap-2 mt-5">{r.approved?<button onClick={()=>update(r.id,false)} className="px-4 py-2 rounded-xl bg-slate-700 text-white">Yayından Kaldır</button>:<button onClick={()=>update(r.id,true)} className="px-4 py-2 rounded-xl bg-green-600 text-white">Onayla ve Yayınla</button>}<button onClick={()=>remove(r)} className="px-4 py-2 rounded-xl bg-red-50 text-red-700 border border-red-200">Sil</button></div></article>)}</div>}</section></main>
}